name: A workflow for my Hello GitHub file
on: push

jobs:
  build:
    name: Hello GitHub action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
